services:
  uptime-kuma:
    image: louislam/uptime-kuma:${UPTIME_KUMA_VERSION}
    restart: unless-stopped
    ports:
      - "3001:3001"

    environment:
      TZ: ${TZ}

    volumes:
      - ./data:/app/data
